
### Задачи
GET http://localhost:38109/treasury/status

### report
GET http://localhost:38109/report/api/projects-db

### Настройки задачи
GET http://localhost:38109/zp/settings-xml?task_id=92ca9a3d-a8dc-4690-9ecc-2e34265f8c76


### Команды pending
GET http://localhost:10993/zp/commands?status=pending

### Создать команду
POST http://localhost:38109/treasury/update?maxId=2
Content-Type: application/json

{
  
}

### PM Bridge — пометить выполненной
POST http://localhost:10993/zp/commands/done
Content-Type: application/json

{
  "id": "uuid-сюда",
  "result": "ok",
  "status": "done"
}


### getBrowserInfo
GET http://localhost:8160/v1/getBrowserInfo
Api-Token: C6HgTYHO-IPBb4tQxA8gjwqyonR0qkP3